#!/usr/bin/env python3

# region copyright
# Copyright 2023-2026 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

import os
import sys

import click

from src.python.config import c as config
from src.python.debug import debug_break  # noqa
from src.python.deploy_command import DeployCommand
from src.python.deployer import Deployer
from src.python.utils import (
    colorize_error,
    colorize_info,
    colorize_prompt,
    gcp_login,
    shell_command,
)


class DeployGCPCommand(DeployCommand):
    """
    Defines options specific for "deploy-gcp" command.
    """

    # gcp instance types capable of running isaac
    GCP_OVKIT_INSTANCE_TYPES = (
        [f"g2-standard-{i}" for i in [4, 8, 12, 16, 24, 32, 48, 96]]
        + [f"n1-standard-{i}" for i in [4, 8, 16, 32, 64, 96]]
        + [f"n1-highmem-{i}" for i in [4, 8, 16, 32, 64, 96]]
        + [f"n1-highcpu-{i}" for i in [16, 32, 64, 96]]
        + [f"a2-highgpu-{i}g" for i in [1, 2, 4, 8]]
        + [f"g4-standard-{i}" for i in [48, 96, 192, 384]]
    )

    @staticmethod
    def project_callback(ctx, param, value):
        if value == "":
            raise click.BadParameter(colorize_error("Project ID cannot be empty"))
        return value

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # --zone

        help_message = (
            "Zone (see https://cloud.google.com/compute/docs/gpus/gpu-regions-zones "
            + "for NVIDIA RTX virtual workstations availability)"
        )

        self.params.insert(
            # insert before --isaac option
            self.param_index("isaacsim"),
            click.core.Option(
                ("--zone",),
                prompt=colorize_prompt(f"* {help_message}"),
                callback=lambda ctx, param, value: value.lower(),
                default="us-central1-a",
                show_default=True,
                help=help_message,
            ),
        )

        # --project-id

        help_message = (
            "Project ID (see https://console.cloud.google.com/cloud-resource-manager)"
        )

        self.params.insert(
            # insert after --zone option
            self.param_index("zone") + 1,
            click.core.Option(
                ("--project",),
                prompt=colorize_prompt(f"* {help_message}"),
                callback=self.project_callback,
                default=shell_command(
                    "gcloud config list --format 'value(core.project)'",
                    verbose=False,
                    exit_on_error=False,
                    capture_output=True,
                )
                .stdout.decode("utf-8")
                .strip(),
                help=help_message,
            ),
        )

        # --instance-type

        self.params.insert(
            # insert before --ingress-cidrs option
            self.param_index("ingress_cidrs"),
            click.core.Option(
                (
                    "--instance-type",
                    "--isaac-workstation-instance-type",
                    "isaac_workstation_instance_type",
                ),
                prompt=colorize_prompt(
                    "* Instance Type "
                    + "(see https://cloud.google.com/compute/docs/general-purpose-machines for details)"
                ),
                type=click.Choice(self.GCP_OVKIT_INSTANCE_TYPES),
                show_default=True,
                default=config["gcp_default_isaac_workstation_instance_type"],
                help="Instance type.",
            ),
        )

        # --isaac-workstation-gpu-count

        self.params.insert(
            # insert after --isaac-instance-type option
            self.param_index("isaac_workstation_instance_type") + 1,
            click.core.Option(
                ("--isaac-workstation-gpu-count",),
                prompt=colorize_prompt(
                    "* Isaac Sim: Number of GPUs. N1 - up to 4x NVIDIA T4; "
                    + "G2 - up to 8x NVIDIA L4; G4 - up to 8x NVIDIA RTX PRO 60000 GPUs."
                ),
                show_default=True,
                type=click.Choice(["1", "2", "4", "8"]),
                default=str(config["gcp_default_isaac_workstation_gpu_count"]),
                help="Number of GPUs to attach to Isaac Sim instance.",
            ),
        )

        # --flex-start/--no-flex-start

        self.params.insert(
            # insert before --ingress-cidrs option
            self.param_index("ingress_cidrs"),
            click.core.Option(
                ("--flex-start/--no-flex-start",),
                default=False,
                show_default=True,
                help="Deploy using GCP Flex-start (Dynamic Workload Scheduler).",
            ),
        )

        # --spot/--no-spot
        self.params.insert(
            self.param_index("flex_start"),
            click.core.Option(
                ("--spot/--no-spot",),
                default=False,
                show_default=True,
                help="Deploy as GCP Spot VM (preemptible with 60-91% discount and automated backup).",
            ),
        )

        # --backup-bucket

        self.params.insert(
            # insert after --flex-start option
            self.param_index("flex_start") + 1,
            click.core.Option(
                ("--backup-bucket",),
                default="",
                show_default=False,
                help="GCS bucket name for continuous checkpoints & preemption backups.",
            ),
        )

        # --auto-restore/--no-auto-restore

        self.params.insert(
            # insert after --backup-bucket option
            self.param_index("backup_bucket") + 1,
            click.core.Option(
                ("--auto-restore/--no-auto-restore",),
                default=False,
                show_default=True,
                help="Automatically restore existing results/checkpoints from GCS on startup.",
            ),
        )


class GCPDeployer(Deployer):
    """
    Deploys stuff to GCP
    """

    def __init__(self, params, config):
        super().__init__(params, config)

    def main(self):
        # ask what to do if deployment already exists
        self.ask_existing_behavior()

        if self.existing_behavior != "run_ansible":
            # create tfvars file, deal with existing deployment
            instance_type = self.params["isaac_workstation_instance_type"]
            instance_type_prefix = instance_type[:2]
            boot_disk_type = (
                "hyperdisk-balanced" if instance_type_prefix == "g4" else "pd-ssd"
            )

            gpu_type = {
                "g2": "nvidia-l4",
                "n1": "nvidia-tesla-t4",
                "a2": "nvidia-tesla-a100",
                "g4": "nvidia-rtx-pro-6000",
            }.get(instance_type_prefix, "nvidia-l4")

            # Determine GPU count automatically if multi-GPU machine type
            user_gpu_count = self.params.get("isaac_workstation_gpu_count")
            if user_gpu_count and str(user_gpu_count) != "1":
                gpu_count = int(user_gpu_count)
            elif "24" in instance_type or "2g" in instance_type:
                gpu_count = 2
            elif "48" in instance_type or "4g" in instance_type:
                gpu_count = 4
            elif "96" in instance_type or "8g" in instance_type:
                gpu_count = 8
            else:
                gpu_count = 1

            use_spot = self.params.get("spot", False)
            backup_bucket = self.params.get("backup_bucket", "")
            if use_spot and not backup_bucket:
                backup_bucket = f"{self.params['project']}-{self.params['deployment_name']}-backups"
                self.params["backup_bucket"] = backup_bucket
                self.params["auto_restore"] = True

            self.create_tfvars(
                {
                    "zone": self.params["zone"],
                    "project": self.params["project"],
                    "isaac_workstation_gpu_count": gpu_count,
                    "isaac_workstation_gpu_type": gpu_type,
                    "boot_disk_type": boot_disk_type,
                    "use_flex_start": self.params.get("flex_start", False),
                    "use_spot": use_spot,
                }
            )


            # login into gcp
            gcp_login(verbose=self.params["debug"])

            if self.params.get("dry_run", False):
                click.echo(colorize_info("\n" + "=" * 70))
                click.echo(colorize_info("* [DRY-RUN] Validating Terraform and Ansible configuration..."))
                click.echo(colorize_info("=" * 70 + "\n"))
                self.initialize_terraform(cwd=f"{config['terraform_dir']}/gcp")
                self.plan_terraform(cwd=f"{config['terraform_dir']}/gcp")
                self.validate_ansible()
                click.echo(colorize_info("\n" + "=" * 70))
                click.echo(colorize_info("* [DRY-RUN] SUCCESS: Terraform plan and Ansible syntax checks passed!"))
                click.echo(colorize_info("* No cloud resources were provisioned and no costs were incurred."))
                click.echo(colorize_info("=" * 70 + "\n"))
                return

            # run terraform
            click.echo(colorize_info("* Running Terraform..."))
            self.initialize_terraform(cwd=f"{config['terraform_dir']}/gcp")
            self.run_terraform(cwd=f"{config['terraform_dir']}/gcp")

        # create ansible inventory file
        self.create_ansible_inventory()

        # export ssh key from terraform
        self.export_ssh_key()

        # save instructions
        self.output_deployment_info(print_text=False)

        # run ansible
        self.run_all_ansible()

        # upload user data
        if self.params["upload"]:
            self.upload_user_data()

        # connection info for the user
        self.output_deployment_info()


@click.command(cls=DeployGCPCommand)
def main(**params):
    GCPDeployer(params, config).main()


if __name__ == "__main__":
    if os.path.exists("/.dockerenv"):
        # we're in docker, run command
        main()
    else:
        # we're outside, start docker container first
        shell_command(f"./run '{' '.join(sys.argv)}'", verbose=True)
