#!/usr/bin/env python3

# region copyright
# Copyright 2023-2026 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

import os
import sys
from datetime import date

import click

from src.python.aws import aws_image_credentials
from src.python.config import c as config
from src.python.debug import debug_break, debug_start  # noqa
from src.python.deploy_command import DeployCommand
from src.python.image_command_utils import configure_image_preview, forward_image_command, local_image_mode, preview_image_build, run_packer_build
from src.python.utils import (
    colorize_error,
    colorize_info,
    colorize_prompt,
    shell_command,
)


class ImageAWSCommand(DeployCommand):
    """
    Defines options specific for "image-aws" command.
    """

    # supported AWS instance types (same as deploy-aws)
    AWS_OVKIT_INSTANCE_TYPES = [
        "g4dn.2xlarge",
        "g4dn.4xlarge",
        "g4dn.8xlarge",
        "g4dn.16xlarge",
        "g4dn.12xlarge",
        "g4dn.metal",
        "g5.2xlarge",
        "g5.4xlarge",
        "g5.8xlarge",
        "g5.16xlarge",
        "g5.12xlarge",
        "g5.24xlarge",
        "g5.48xlarge",
        "g6.2xlarge",
        "g6.4xlarge",
        "g6.8xlarge",
        "g6.16xlarge",
        "gr6.4xlarge",
        "gr6.8xlarge",
        "g6.12xlarge",
        "g6.24xlarge",
        "g6.48xlarge",
        "g6e.xlarge",
        "g6e.2xlarge",
        "g6e.4xlarge",
        "g6e.8xlarge",
        "g6e.12xlarge",
        "g6e.16xlarge",
        "g6e.24xlarge",
        "g6e.48xlarge",
    ]

    @staticmethod
    def ovkit_instance_type_callback(ctx, param, value):
        if "g5.xlarge" == value:
            raise click.BadParameter(colorize_error("g5.xlarge is not supported. "))

        if value not in ImageAWSCommand.AWS_OVKIT_INSTANCE_TYPES:
            raise click.BadParameter(
                colorize_error(
                    f"Invalid instance type: {value}. Choose one of: "
                    + ", ".join(ImageAWSCommand.AWS_OVKIT_INSTANCE_TYPES)
                    + "."
                )
            )

        return value

    def make_context(self, info_name, args, parent=None, **extra):
        """Allow image name as an unnamed first argument."""
        args = list(args)
        if args and not args[0].startswith("-") and "--image-name" not in args:
            args = ["--image-name", args[0]] + args[1:]
        return click.core.Command.make_context(
            self, info_name, args, parent=parent, **extra
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        configure_image_preview(self)

        # remove params not applicable to image building
        self.params = [
            p
            for p in self.params
            if p.name
            not in (
                "in_china",
                "from_image",
                "ingress_cidrs",
                "vnc_password",
                "upload",
                "deployment_name",
            )
        ]

        # --image-name (insert first so it's prompted before other options)
        self.params.insert(
            0,
            click.core.Option(
                ("--image-name",),
                show_default="<current date>",
                default=lambda: date.today().strftime("%Y-%m-%d"),
                help="AMI name. Will be prefixed with 'isaacautomator.isaacworkstation.'."
                " When deploying with --from-image, Terraform picks the most recent AMI"
                " matching this prefix.",
                prompt=colorize_prompt(
                    "* AMI name (will be prefixed with 'isaacautomator.isaacworkstation.')"
                ),
            ),
        )

        # replace --existing with overwrite/fail
        self.params = [p for p in self.params if p.name != "existing"]
        self.params.insert(
            len(self.params),
            click.core.Option(
                ("--existing",),
                type=click.Choice(["overwrite", "fail"]),
                default="fail",
                show_default=True,
                help="What to do if an AMI with the same name already exists:"
                " 'overwrite' will delete the old AMI first,"
                " 'fail' will abort the build.",
            ),
        )

        # --instance-type
        self.params.insert(
            len(self.params),
            click.core.Option(
                (
                    "--instance-type",
                    "--isaac-workstation-instance-type",
                    "isaac_workstation_instance_type",
                ),
                prompt=colorize_prompt(
                    "* Instance Type for Packer build "
                    + "(G5, G4dn, G6 and G6e are supported, see https://docs.aws.amazon.com/dlami/latest/devguide/gpu.html)"
                ),
                show_default=True,
                default=config["aws_default_isaac_workstation_instance_type"],
                callback=ImageAWSCommand.ovkit_instance_type_callback,
                help="Instance type for the Packer build instance. Currently supported: "
                + ", ".join(self.AWS_OVKIT_INSTANCE_TYPES)
                + ".",
            ),
        )

        # --region
        self.params.insert(
            len(self.params),
            click.core.Option(
                ("--region",),
                show_default=True,
                default="US East 1",
                help="AWS Region. Can be entered as 'us-east-1' or 'US East 1'."
                " See https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
                prompt=colorize_prompt(
                    "* AWS Region (e.g. us-east-1 or US East 1,"
                    " see https://aws.amazon.com/about-aws/global-infrastructure/regions_az/)"
                ),
                callback=lambda ctx, param, value: value.lower().replace(" ", "-"),
            ),
        )

        # --image-name is already inserted above


def build_ami(params, config):
    """
    Build AWS AMI using Packer.
    """

    debug = params["debug"]
    region = params["region"]
    instance_type = params["isaac_workstation_instance_type"]
    isaacsim = params["isaacsim"]
    isaaclab = params["isaaclab"]
    isaaclab_arena = params["isaaclab_arena"]
    system_user_password = params["system_user_password"]
    image_name = params.get("image_name", "")
    existing = params["existing"]

    # use image name as deployment name
    params["deployment_name"] = image_name or "aws-image"

    version = os.environ.get("VERSION") or None
    if params.get("dry_run", False):
        # Host previews do not run ./run to resolve VERSION; render it as null.
        return preview_image_build("aws", params, version)

    if not version:
        click.echo(colorize_error("Error: VERSION environment variable is not set."))
        sys.exit(1)

    # load AWS credentials only for an actual build
    creds = aws_image_credentials(verbose=debug)

    # Only the Packer child receives explicit credentials; retain ambient auth.
    packer_env = {key.upper(): creds[key] for key in (
        "aws_access_key_id", "aws_secret_access_key", "aws_session_token"
    ) if creds.get(key)}

    packer_dir = f"{config['app_dir']}/src/packer/aws/isaac-workstation.pkr.hcl"

    demos = params.get("demos", "no")
    packer_vars = {
        "aws_region": region,
        "instance_type": instance_type,
        "version": version,
        "system_user_password": system_user_password,
        "isaacsim": isaacsim,
        "isaaclab": isaaclab,
        "isaaclab_arena": isaaclab_arena,
        "demos": demos,
        "in_china": False,
    }

    if "install_gr00t" in params:
        packer_vars["install_gr00t"] = bool(params["install_gr00t"])
    if "enable_neo4j" in params:
        packer_vars["enable_neo4j"] = bool(params["enable_neo4j"])

    if image_name:
        full_image_name = f"isaacautomator.isaacworkstation.{image_name}"
        packer_vars["image_name"] = full_image_name

    click.echo(colorize_info("* Building AWS AMI with Packer..."))

    run_packer_build(packer_dir, packer_vars, debug=debug,
                     env=packer_env, force=existing == "overwrite")

    click.echo(colorize_info("* AMI build complete!"))


@click.command(cls=ImageAWSCommand)
def main(**params):
    build_ami(params, config)


if __name__ == "__main__":
    if os.path.exists("/.dockerenv") or local_image_mode(main):
        main()
    else:
        sys.exit(forward_image_command(__file__))
