package main
import("context";"database/sql";"encoding/json";"fmt";"os";"path/filepath";"sort"
 "github.com/cycloidio/terracost";"github.com/cycloidio/terracost/mysql";"github.com/cycloidio/terracost/product";"github.com/cycloidio/terracost/price";"github.com/cycloidio/terracost/usage";"github.com/shopspring/decimal";_ "github.com/go-sql-driver/mysql")
func must(e error){if e!=nil {panic(e)}}
func main(){ctx:=context.Background();db,e:=sql.Open("mysql","root@tcp(isaac-cost-terra-db:3306)/terracost_test?multiStatements=true");must(e);defer db.Close();must(db.PingContext(ctx));must(mysql.Migrate(ctx,db,"pricing_migrations"));be:=mysql.NewBackend(db)
 seed:=func(mt string){p:=&product.Product{Provider:"google",SKU:"SYNTHETIC-NOT-VENDOR-"+mt,Service:"Compute Engine",Family:"Compute",Location:"us-west1",Attributes:map[string]string{"machine_type":mt}};p.ID,e=be.Products().Upsert(ctx,p);must(e);_,e=be.Prices().Upsert(ctx,&price.WithProduct{Product:p,Price:price.Price{Currency:"USD",Unit:"h",Value:decimal.RequireFromString("1.25")}});must(e)}
 seed("n2-standard-2");p,e:=be.Products().FindByVendorAndSKU(ctx,"google","SYNTHETIC-NOT-VENDOR-n2-standard-2");must(e);prices,e:=be.Prices().Filter(ctx,p.ID,&price.Filter{});must(e);fmt.Printf("MYSQL_LOOKUP synthetic sku=%s prices=%d value=%s\n",p.SKU,len(prices),prices[0].Value)
 files,e:=filepath.Glob("/trial/plans/*.json");must(e);sort.Strings(files)
 for _,phase:=range []string{"missing_g4","synthetic_g4_seed"}{if phase=="synthetic_g4_seed"{seed("g4-standard-48");seed("g4-standard-384")};for _,path:=range files{f,e:=os.Open(path);must(e);plan,e:=terracost.EstimateTerraformPlan(ctx,be,f,usage.Default);f.Close();row:=map[string]interface{}{"phase":phase,"input":filepath.Base(path),"input_kind":"exported-plan-shaped synthetic; NOT terraform-generated","pricing":"synthetic SQL protocol seed; NOT vendor pricing"};if e!=nil{row["top_error"]=e.Error()}else{total,err:=plan.PlannedCost();row["total"]=total;row["total_error"]=fmt.Sprint(err);row["skipped"]=plan.SkippedAddresses();rs:=[]interface{}{};for _,d:=range plan.ResourceDifferences(){c,er:=d.PlannedCost();errors:=map[string]string{};for k,v:=range d.Errors(){errors[k]=v.Error()};rs=append(rs,map[string]interface{}{"address":d.Address,"cost":c,"cost_error":fmt.Sprint(er),"valid":d.Valid(),"errors":errors,"components":d.ComponentDiffs})};row["resources"]=rs};b,e:=json.Marshal(row);must(e);fmt.Println(string(b))}}
}
